apiVersion: v1
kind: Namespace
metadata:
    name: $namespace

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: $namespace
    name: $pvcName
  nfs:
    path: $path
    server: $nfsIp  #change to your nfs server ip here

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $namespace
 name: $pvcName
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
