# The Fabric cluster name
clusterName: mycluster

# consensus type: kafka, solo.
consensusType: kafka

# The network mode used by Hyperledger Fabric. It can be bridge or host.
networkMode: bridge
# The directory of dockerd sock file on the host.
dockerdSockDir: /var/run

# The starting listen port for Fabric Service
fabricPortStartFrom: 30000

# NFS server configurations   
nfsServer: 10.160.0.5
  # FQDN of IP of NFS Server 
  hostname: nfs
  # The path of NFS export dir
  exportDir: /opt/share
  # The local mount point for remote NFS Server
  mountPoint: /mnt/nfs

# Hyperledger Fabric image tag
hyperledgerFabricImage:
  fabricTag: 1.1.0
  fabricKafkaTag: 0.4.7

#defaufchannelName
channelName: defaultchannel
  
crypto-config.yaml:
# Refer to https://github.com/hyperledger/fabric/blob/release-1.1/examples/e2e_cli/crypto-config.yaml
  OrdererOrgs:
    - Name: Orderer
      Domain: orderer.example.com
      CA:
        Country: US
        Province: California
        Locality: San Francisco
      Template:
        Count: 1
  PeerOrgs:
    - Name: Org1
      Domain: org1.example.com
      EnableNodeOUs: true
      CA:
        Country: US
        Province: California
        Locality: San Francisco
      Template:
        Count: 2
      Users:
        Count: 1
    - Name: Org2
      Domain: org2.example.com
      EnableNodeOUs: true
      CA:
        Country: US
        Province: California
        Locality: San Francisco
      Template:
        Count: 2
      Users:
        Count: 1

